### ISSUE TITLE
Mutating new object mutates the original object

### ISSUE THREAD

**Issue by denchen** [RebeccaStevens/deepmerge-ts#497] opened 2024-08-08 23:47 UTC
## Bug Report

After creating a new object with `deepmerge()`, if I update the new object, the original object gets updated as well.

### Expected behavior

No matter what I do to the new merged object, the original input objects should remain unmodified

### Actual behavior

Updating the new object also mutates the original objects

### Steps to reproduce

```typescript
import { deepmerge } from "deepmerge-ts";
import prettyFormat from "pretty-format";

const A = {
  foo: {}
};
const B = {};
const newObject = deepmerge(A, B);

console.log("pre-modified A:", prettyFormat(A));
console.log("pre-modified newObject:", prettyFormat(newObject));

newObject.foo.bar = "a";

console.log("post-modified A:", prettyFormat(A));
console.log("post-modified newObject:", prettyFormat(newObject));
```

Output:
```
pre-modified A: Object {
  "foo": Object {},
}
pre-modified newObject: Object {
  "foo": Object {},
}
post-modified A: Object {
  "foo": Object {
    "bar": "a",
  },
}
post-modified newObject: Object {
  "foo": Object {
    "bar": "a",
  },
}
```

https://codesandbox.io/s/deepmerge-ts-example-forked-5f6kn6?file=/src/index.ts

The workaround I'm using now is to `structureClone()` the initial object first, like such:

```typescript
const newObject = deepmerge(structuredClone(A), B);
```

**Comment by RebeccaStevens** [comment] 2024-08-09 05:14
This is by design. If you want to make the returned object have no references to the inputs, you need to manually clone. You can either clone the entire returned object, or use a custom merge to clone only the parts that need cloneing.

To clone along the way, use `deepmergeCustom` and supply a `mergeOther` function that looks a bit like this:

```ts
(values, utils, meta) => {
  cloneDeep(utils.defaultMergeFunctions.mergeOthers(values)),
}
```

You'll need to provide your own `cloneDeep` function.

The main reason we can't support this out of the box is because we don't know how to clone every possible object. For example, if we receive a `Date` how do we clone that? Does it need to be clone in the first place? That's out of scope of this project; so you need to decide how that case is handled.

**Closed by RebeccaStevens** 2024-08-09 05:14 UTC
Labels: Status: Triage, Type: Bug

**Comment by denchen** [comment] 2024-08-09 05:21
Thanks for the explanation, and it does make sense. However, I do think this should be documented somewhere, as I did scour the README / docs to see if there was a section on the behavior of `deepmerge()`. If it's there, then I missed it.
