### ISSUE TITLE
version 5 causes runtime error with Safari 14

### ISSUE THREAD

**Issue by caffeinated-pixels** [RebeccaStevens/deepmerge-ts#416] opened 2023-11-07 21:05 UTC
## Bug Report
Updating `deepmerge-ts` from v4.3.0 to v5.1.0 in our NextJS app started consistently causing unhandled runtime errors in Safari 14 (but not in newer versions of Safari). Reverting to 4.3.0 resolved the issue.

### Expected behavior
Many of our users are still on Safari 14, so it would be nice if newer versions of `deepmerge-ts` still supported Safari 14.

### Actual behavior
On Safari 14, we're consistently seeing an unhandled runtime error, specifically `TypeError: values.at is not a function. (In 'values.at(-1)', 'values.at' is undefined)`.

I've noticed that 'values.at(-1)' relates to changes made to `src/defaults/into.ts` and `src/defaults/vanilla.ts`

![CleanShot 2023-11-07 at 16 01 17](https://github.com/RebeccaStevens/deepmerge-ts/assets/29311273/613eba1c-e59a-4ae7-a611-b68b7b3c3cb9)

### Steps to reproduce
Run an app that uses `deepmerge-ts` v5 in Safari 14 (we've been doing our testing in Browserstack).

**Comment by RebeccaStevens** [comment] 2023-11-08 01:19
Duplicate of #411

**Closed by RebeccaStevens** 2023-11-08 01:19 UTC
Labels: Status: Triage, Type: Bug

**Comment by fritzfelix** [comment] 2024-07-22 09:48
Reopening the discussion around this https://github.com/RebeccaStevens/deepmerge-ts/issues/487.
