### ISSUE TITLE
Remove usage of Array.at

### ISSUE THREAD

**Issue by stnor** [RebeccaStevens/deepmerge-ts#430] opened 2024-01-23 12:43 UTC
## Bug Report
Array.at isn't available in some browsers, like iOS 12.5

### Proposed changes

Replace the two occurrences of
```values.at(-1)```with ```values[values.length-1]```
to make this library work fine in those browsers.

**Comment by RebeccaStevens** [comment] 2024-01-23 19:30
Duplicate of #411

**Closed by RebeccaStevens** 2024-01-23 19:30 UTC
Labels: Resolution: Won't Fix, Resolution: Duplicate
